// <auto-generated />
using System;
using EIIOS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EIIOS.Migrations
{
    [DbContext(typeof(EIIOSDbContext))]
    [Migration("20250924095510_DbPopulate")]
    partial class DbPopulate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EIIOS.Models.AllergenModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Allergens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "GLU",
                            Name = "Gluten"
                        },
                        new
                        {
                            Id = 2,
                            Code = "NUT",
                            Name = "Nuts"
                        },
                        new
                        {
                            Id = 3,
                            Code = "DUI",
                            Name = "Dairy"
                        },
                        new
                        {
                            Id = 4,
                            Code = "EGA",
                            Name = "Eggs"
                        },
                        new
                        {
                            Id = 5,
                            Code = "SOY",
                            Name = "Soy"
                        },
                        new
                        {
                            Id = 6,
                            Code = "FIS",
                            Name = "Fish"
                        },
                        new
                        {
                            Id = 7,
                            Code = "SHE",
                            Name = "Shellfish"
                        },
                        new
                        {
                            Id = 8,
                            Code = "CEL",
                            Name = "Celery"
                        },
                        new
                        {
                            Id = 9,
                            Code = "MUS",
                            Name = "Mustard"
                        },
                        new
                        {
                            Id = 10,
                            Code = "SES",
                            Name = "Sesame Seeds"
                        },
                        new
                        {
                            Id = 11,
                            Code = "LUP",
                            Name = "Lupin"
                        },
                        new
                        {
                            Id = 12,
                            Code = "SUL",
                            Name = "Sulphites"
                        });
                });

            modelBuilder.Entity("EIIOS.Models.CategoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Appetizers and small plates",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Starters"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Hearty and filling meals",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Main Courses"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Sweet treats to finish your meal",
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Desserts"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Drinks and refreshments",
                            DisplayOrder = 4,
                            IsActive = true,
                            Name = "Beverages"
                        });
                });

            modelBuilder.Entity("EIIOS.Models.DailyMenuItemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DailyMenuId")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal?>("SpecialPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("DailyMenuId");

                    b.HasIndex("ProductId");

                    b.ToTable("DailyMenuItems");
                });

            modelBuilder.Entity("EIIOS.Models.DailyMenuModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("MenuDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("MenuDate")
                        .IsUnique();

                    b.ToTable("DailyMenus");
                });

            modelBuilder.Entity("EIIOS.Models.DiscountModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("DiscountValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("EIIOS.Models.DiscountProductModel", b =>
                {
                    b.Property<int>("DiscountId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("DiscountId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("DiscountProducts");
                });

            modelBuilder.Entity("EIIOS.Models.InventoryItemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("CurrentQuantity")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("MinimumQuantity")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("UnitCost")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("InventoryItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 24, 9, 55, 9, 338, DateTimeKind.Utc).AddTicks(797),
                            CurrentQuantity = 50m,
                            MinimumQuantity = 5m,
                            Name = "Chicken Breast",
                            Unit = "kg",
                            UnitCost = 6.50m,
                            UpdatedAt = new DateTime(2025, 9, 24, 9, 55, 9, 338, DateTimeKind.Utc).AddTicks(797)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 9, 24, 9, 55, 9, 338, DateTimeKind.Utc).AddTicks(800),
                            CurrentQuantity = 100m,
                            MinimumQuantity = 10m,
                            Name = "Flour",
                            Unit = "kg",
                            UnitCost = 1.20m,
                            UpdatedAt = new DateTime(2025, 9, 24, 9, 55, 9, 338, DateTimeKind.Utc).AddTicks(800)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 9, 24, 9, 55, 9, 338, DateTimeKind.Utc).AddTicks(803),
                            CurrentQuantity = 30m,
                            MinimumQuantity = 5m,
                            Name = "Milk",
                            Unit = "l",
                            UnitCost = 0.90m,
                            UpdatedAt = new DateTime(2025, 9, 24, 9, 55, 9, 338, DateTimeKind.Utc).AddTicks(803)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 9, 24, 9, 55, 9, 338, DateTimeKind.Utc).AddTicks(805),
                            CurrentQuantity = 200m,
                            MinimumQuantity = 20m,
                            Name = "Eggs",
                            Unit = "pieces",
                            UnitCost = 0.15m,
                            UpdatedAt = new DateTime(2025, 9, 24, 9, 55, 9, 338, DateTimeKind.Utc).AddTicks(806)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 9, 24, 9, 55, 9, 338, DateTimeKind.Utc).AddTicks(808),
                            CurrentQuantity = 40m,
                            MinimumQuantity = 5m,
                            Name = "Lamb Meat",
                            Unit = "kg",
                            UnitCost = 9.50m,
                            UpdatedAt = new DateTime(2025, 9, 24, 9, 55, 9, 338, DateTimeKind.Utc).AddTicks(808)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 9, 24, 9, 55, 9, 338, DateTimeKind.Utc).AddTicks(810),
                            CurrentQuantity = 30m,
                            MinimumQuantity = 5m,
                            Name = "Beef Mince",
                            Unit = "kg",
                            UnitCost = 8.00m,
                            UpdatedAt = new DateTime(2025, 9, 24, 9, 55, 9, 338, DateTimeKind.Utc).AddTicks(810)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 9, 24, 9, 55, 9, 338, DateTimeKind.Utc).AddTicks(812),
                            CurrentQuantity = 300m,
                            MinimumQuantity = 50m,
                            Name = "Pita Bread",
                            Unit = "pieces",
                            UnitCost = 0.40m,
                            UpdatedAt = new DateTime(2025, 9, 24, 9, 55, 9, 338, DateTimeKind.Utc).AddTicks(813)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 9, 24, 9, 55, 9, 338, DateTimeKind.Utc).AddTicks(815),
                            CurrentQuantity = 200m,
                            MinimumQuantity = 30m,
                            Name = "Tortilla Wraps",
                            Unit = "pieces",
                            UnitCost = 0.50m,
                            UpdatedAt = new DateTime(2025, 9, 24, 9, 55, 9, 338, DateTimeKind.Utc).AddTicks(815)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 9, 24, 9, 55, 9, 338, DateTimeKind.Utc).AddTicks(817),
                            CurrentQuantity = 15m,
                            MinimumQuantity = 2m,
                            Name = "Lettuce",
                            Unit = "kg",
                            UnitCost = 1.80m,
                            UpdatedAt = new DateTime(2025, 9, 24, 9, 55, 9, 338, DateTimeKind.Utc).AddTicks(818)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 9, 24, 9, 55, 9, 338, DateTimeKind.Utc).AddTicks(820),
                            CurrentQuantity = 20m,
                            MinimumQuantity = 3m,
                            Name = "Tomatoes",
                            Unit = "kg",
                            UnitCost = 2.20m,
                            UpdatedAt = new DateTime(2025, 9, 24, 9, 55, 9, 338, DateTimeKind.Utc).AddTicks(820)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 9, 24, 9, 55, 9, 338, DateTimeKind.Utc).AddTicks(822),
                            CurrentQuantity = 25m,
                            MinimumQuantity = 3m,
                            Name = "Onions",
                            Unit = "kg",
                            UnitCost = 1.50m,
                            UpdatedAt = new DateTime(2025, 9, 24, 9, 55, 9, 338, DateTimeKind.Utc).AddTicks(822)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 9, 24, 9, 55, 9, 338, DateTimeKind.Utc).AddTicks(824),
                            CurrentQuantity = 10m,
                            MinimumQuantity = 2m,
                            Name = "Cabbage",
                            Unit = "kg",
                            UnitCost = 1.70m,
                            UpdatedAt = new DateTime(2025, 9, 24, 9, 55, 9, 338, DateTimeKind.Utc).AddTicks(825)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 9, 24, 9, 55, 9, 338, DateTimeKind.Utc).AddTicks(827),
                            CurrentQuantity = 12m,
                            MinimumQuantity = 2m,
                            Name = "Cucumbers",
                            Unit = "kg",
                            UnitCost = 2.00m,
                            UpdatedAt = new DateTime(2025, 9, 24, 9, 55, 9, 338, DateTimeKind.Utc).AddTicks(827)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 9, 24, 9, 55, 9, 338, DateTimeKind.Utc).AddTicks(891),
                            CurrentQuantity = 10m,
                            MinimumQuantity = 2m,
                            Name = "Yogurt",
                            Unit = "kg",
                            UnitCost = 3.50m,
                            UpdatedAt = new DateTime(2025, 9, 24, 9, 55, 9, 338, DateTimeKind.Utc).AddTicks(891)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 9, 24, 9, 55, 9, 338, DateTimeKind.Utc).AddTicks(896),
                            CurrentQuantity = 5m,
                            MinimumQuantity = 1m,
                            Name = "Garlic",
                            Unit = "kg",
                            UnitCost = 4.00m,
                            UpdatedAt = new DateTime(2025, 9, 24, 9, 55, 9, 338, DateTimeKind.Utc).AddTicks(896)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2025, 9, 24, 9, 55, 9, 338, DateTimeKind.Utc).AddTicks(898),
                            CurrentQuantity = 8m,
                            MinimumQuantity = 2m,
                            Name = "Chili Sauce",
                            Unit = "l",
                            UnitCost = 5.00m,
                            UpdatedAt = new DateTime(2025, 9, 24, 9, 55, 9, 338, DateTimeKind.Utc).AddTicks(899)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2025, 9, 24, 9, 55, 9, 338, DateTimeKind.Utc).AddTicks(901),
                            CurrentQuantity = 6m,
                            MinimumQuantity = 1m,
                            Name = "Tahini Sauce",
                            Unit = "l",
                            UnitCost = 6.00m,
                            UpdatedAt = new DateTime(2025, 9, 24, 9, 55, 9, 338, DateTimeKind.Utc).AddTicks(901)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2025, 9, 24, 9, 55, 9, 338, DateTimeKind.Utc).AddTicks(904),
                            CurrentQuantity = 25m,
                            MinimumQuantity = 5m,
                            Name = "French Fries",
                            Unit = "kg",
                            UnitCost = 2.50m,
                            UpdatedAt = new DateTime(2025, 9, 24, 9, 55, 9, 338, DateTimeKind.Utc).AddTicks(904)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2025, 9, 24, 9, 55, 9, 338, DateTimeKind.Utc).AddTicks(906),
                            CurrentQuantity = 15m,
                            MinimumQuantity = 3m,
                            Name = "Olive Oil",
                            Unit = "l",
                            UnitCost = 7.00m,
                            UpdatedAt = new DateTime(2025, 9, 24, 9, 55, 9, 338, DateTimeKind.Utc).AddTicks(907)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2025, 9, 24, 9, 55, 9, 338, DateTimeKind.Utc).AddTicks(909),
                            CurrentQuantity = 5m,
                            MinimumQuantity = 1m,
                            Name = "Spice Mix (Kebab Seasoning)",
                            Unit = "kg",
                            UnitCost = 12.00m,
                            UpdatedAt = new DateTime(2025, 9, 24, 9, 55, 9, 338, DateTimeKind.Utc).AddTicks(909)
                        });
                });

            modelBuilder.Entity("EIIOS.Models.ProductAllergenModel", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("AllergenId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("ProductId", "AllergenId");

                    b.HasIndex("AllergenId");

                    b.ToTable("ProductAllergens");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            AllergenId = 1
                        },
                        new
                        {
                            ProductId = 1,
                            AllergenId = 3
                        },
                        new
                        {
                            ProductId = 1,
                            AllergenId = 4
                        },
                        new
                        {
                            ProductId = 2,
                            AllergenId = 1
                        },
                        new
                        {
                            ProductId = 2,
                            AllergenId = 3
                        },
                        new
                        {
                            ProductId = 2,
                            AllergenId = 4
                        },
                        new
                        {
                            ProductId = 3,
                            AllergenId = 1
                        },
                        new
                        {
                            ProductId = 3,
                            AllergenId = 10
                        },
                        new
                        {
                            ProductId = 4,
                            AllergenId = 1
                        },
                        new
                        {
                            ProductId = 4,
                            AllergenId = 10
                        },
                        new
                        {
                            ProductId = 5,
                            AllergenId = 3
                        },
                        new
                        {
                            ProductId = 5,
                            AllergenId = 4
                        });
                });

            modelBuilder.Entity("EIIOS.Models.ProductCategoryModel", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 2
                        });
                });

            modelBuilder.Entity("EIIOS.Models.ProductIngredientModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InventoryItemId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("QuantityNeeded")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("InventoryItemId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductIngredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InventoryItemId = 1,
                            ProductId = 1,
                            QuantityNeeded = 0.20m,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 2,
                            InventoryItemId = 8,
                            ProductId = 1,
                            QuantityNeeded = 1m,
                            Unit = "pieces"
                        },
                        new
                        {
                            Id = 3,
                            InventoryItemId = 9,
                            ProductId = 1,
                            QuantityNeeded = 0.05m,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 4,
                            InventoryItemId = 10,
                            ProductId = 1,
                            QuantityNeeded = 0.05m,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 5,
                            InventoryItemId = 11,
                            ProductId = 1,
                            QuantityNeeded = 0.02m,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 6,
                            InventoryItemId = 15,
                            ProductId = 1,
                            QuantityNeeded = 0.01m,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 7,
                            InventoryItemId = 5,
                            ProductId = 2,
                            QuantityNeeded = 0.25m,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 8,
                            InventoryItemId = 7,
                            ProductId = 2,
                            QuantityNeeded = 1m,
                            Unit = "pieces"
                        },
                        new
                        {
                            Id = 9,
                            InventoryItemId = 9,
                            ProductId = 2,
                            QuantityNeeded = 0.05m,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 10,
                            InventoryItemId = 10,
                            ProductId = 2,
                            QuantityNeeded = 0.05m,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 11,
                            InventoryItemId = 11,
                            ProductId = 2,
                            QuantityNeeded = 0.02m,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 12,
                            InventoryItemId = 16,
                            ProductId = 2,
                            QuantityNeeded = 0.02m,
                            Unit = "l"
                        },
                        new
                        {
                            Id = 13,
                            InventoryItemId = 6,
                            ProductId = 3,
                            QuantityNeeded = 0.25m,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 14,
                            InventoryItemId = 20,
                            ProductId = 3,
                            QuantityNeeded = 0.01m,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 15,
                            InventoryItemId = 18,
                            ProductId = 3,
                            QuantityNeeded = 0.15m,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 16,
                            InventoryItemId = 17,
                            ProductId = 3,
                            QuantityNeeded = 0.02m,
                            Unit = "l"
                        },
                        new
                        {
                            Id = 17,
                            InventoryItemId = 8,
                            ProductId = 4,
                            QuantityNeeded = 1m,
                            Unit = "pieces"
                        },
                        new
                        {
                            Id = 18,
                            InventoryItemId = 9,
                            ProductId = 4,
                            QuantityNeeded = 0.05m,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 19,
                            InventoryItemId = 10,
                            ProductId = 4,
                            QuantityNeeded = 0.05m,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 20,
                            InventoryItemId = 13,
                            ProductId = 4,
                            QuantityNeeded = 0.05m,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 21,
                            InventoryItemId = 17,
                            ProductId = 4,
                            QuantityNeeded = 0.02m,
                            Unit = "l"
                        },
                        new
                        {
                            Id = 22,
                            InventoryItemId = 1,
                            ProductId = 5,
                            QuantityNeeded = 0.20m,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 23,
                            InventoryItemId = 18,
                            ProductId = 5,
                            QuantityNeeded = 0.20m,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 24,
                            InventoryItemId = 15,
                            ProductId = 5,
                            QuantityNeeded = 0.01m,
                            Unit = "kg"
                        });
                });

            modelBuilder.Entity("EIIOS.Models.ProductModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("PreparationTime")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 7.50m,
                            CreatedAt = new DateTime(2025, 9, 24, 9, 55, 9, 338, DateTimeKind.Utc).AddTicks(965),
                            CreatedById = 1,
                            Description = "Grilled chicken pieces served in a tortilla wrap with lettuce, tomatoes, onions, and garlic sauce.",
                            IsActive = true,
                            IsAvailable = true,
                            Name = "Chicken Kebab Wrap",
                            PreparationTime = 10,
                            UpdatedAt = new DateTime(2025, 9, 24, 9, 55, 9, 338, DateTimeKind.Utc).AddTicks(966)
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 8.50m,
                            CreatedAt = new DateTime(2025, 9, 24, 9, 55, 9, 338, DateTimeKind.Utc).AddTicks(969),
                            CreatedById = 1,
                            Description = "Thin slices of seasoned lamb served in pita bread with fresh vegetables and chili sauce.",
                            IsActive = true,
                            IsAvailable = true,
                            Name = "Lamb Doner Kebab",
                            PreparationTime = 12,
                            UpdatedAt = new DateTime(2025, 9, 24, 9, 55, 9, 338, DateTimeKind.Utc).AddTicks(969)
                        },
                        new
                        {
                            Id = 3,
                            BasePrice = 9.00m,
                            CreatedAt = new DateTime(2025, 9, 24, 9, 55, 9, 338, DateTimeKind.Utc).AddTicks(972),
                            CreatedById = 1,
                            Description = "Spiced beef mince skewers served with fries and tahini sauce.",
                            IsActive = true,
                            IsAvailable = true,
                            Name = "Beef Kofta Kebab",
                            PreparationTime = 15,
                            UpdatedAt = new DateTime(2025, 9, 24, 9, 55, 9, 338, DateTimeKind.Utc).AddTicks(972)
                        },
                        new
                        {
                            Id = 4,
                            BasePrice = 6.50m,
                            CreatedAt = new DateTime(2025, 9, 24, 9, 55, 9, 338, DateTimeKind.Utc).AddTicks(974),
                            CreatedById = 1,
                            Description = "Crispy falafel balls with lettuce, tomatoes, cucumbers, and tahini sauce in a tortilla wrap.",
                            IsActive = true,
                            IsAvailable = true,
                            Name = "Falafel Wrap",
                            PreparationTime = 8,
                            UpdatedAt = new DateTime(2025, 9, 24, 9, 55, 9, 338, DateTimeKind.Utc).AddTicks(975)
                        },
                        new
                        {
                            Id = 5,
                            BasePrice = 7.00m,
                            CreatedAt = new DateTime(2025, 9, 24, 9, 55, 9, 338, DateTimeKind.Utc).AddTicks(977),
                            CreatedById = 1,
                            Description = "Grilled chicken pieces served over a bed of crispy fries with garlic sauce.",
                            IsActive = true,
                            IsAvailable = true,
                            Name = "Chicken & Fries Box",
                            PreparationTime = 10,
                            UpdatedAt = new DateTime(2025, 9, 24, 9, 55, 9, 338, DateTimeKind.Utc).AddTicks(977)
                        });
                });

            modelBuilder.Entity("EIIOS.Models.StockEntryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("InventoryItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("InventoryItemId");

                    b.ToTable("StockEntries");
                });

            modelBuilder.Entity("EIIOS.Models.TimeEntryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ApprovedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("ClockIn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ClockOut")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("TotalHours")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedById");

                    b.HasIndex("EmployeeId");

                    b.ToTable("TimeEntries");
                });

            modelBuilder.Entity("EIIOS.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 24, 9, 55, 9, 338, DateTimeKind.Utc).AddTicks(695),
                            Email = "admin@eiios.com",
                            FirstName = "System",
                            IsActive = true,
                            IsEmailVerified = true,
                            LastName = "Administrator",
                            PasswordHash = "1234",
                            Role = "Administrator",
                            UpdatedAt = new DateTime(2025, 9, 24, 9, 55, 9, 338, DateTimeKind.Utc).AddTicks(696),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("EIIOS.Models.DailyMenuItemModel", b =>
                {
                    b.HasOne("EIIOS.Models.DailyMenuModel", "DailyMenu")
                        .WithMany("DailyMenuItems")
                        .HasForeignKey("DailyMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EIIOS.Models.ProductModel", "Product")
                        .WithMany("DailyMenuItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DailyMenu");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EIIOS.Models.DailyMenuModel", b =>
                {
                    b.HasOne("EIIOS.Models.UserModel", "CreatedBy")
                        .WithMany("CreatedDailyMenus")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("EIIOS.Models.DiscountModel", b =>
                {
                    b.HasOne("EIIOS.Models.UserModel", "CreatedBy")
                        .WithMany("CreatedDiscounts")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("EIIOS.Models.DiscountProductModel", b =>
                {
                    b.HasOne("EIIOS.Models.DiscountModel", "Discount")
                        .WithMany("DiscountProducts")
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EIIOS.Models.ProductModel", "Product")
                        .WithMany("DiscountProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discount");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EIIOS.Models.ProductAllergenModel", b =>
                {
                    b.HasOne("EIIOS.Models.AllergenModel", "Allergen")
                        .WithMany("ProductAllergens")
                        .HasForeignKey("AllergenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EIIOS.Models.ProductModel", "Product")
                        .WithMany("ProductAllergens")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allergen");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EIIOS.Models.ProductCategoryModel", b =>
                {
                    b.HasOne("EIIOS.Models.CategoryModel", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EIIOS.Models.ProductModel", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EIIOS.Models.ProductIngredientModel", b =>
                {
                    b.HasOne("EIIOS.Models.InventoryItemModel", "InventoryItem")
                        .WithMany("ProductIngredients")
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EIIOS.Models.ProductModel", "Product")
                        .WithMany("ProductIngredients")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryItem");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EIIOS.Models.ProductModel", b =>
                {
                    b.HasOne("EIIOS.Models.UserModel", "CreatedBy")
                        .WithMany("CreatedProducts")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("EIIOS.Models.StockEntryModel", b =>
                {
                    b.HasOne("EIIOS.Models.UserModel", "CreatedBy")
                        .WithMany("CreatedStockEntries")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EIIOS.Models.InventoryItemModel", "InventoryItem")
                        .WithMany("StockEntries")
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("EIIOS.Models.TimeEntryModel", b =>
                {
                    b.HasOne("EIIOS.Models.UserModel", "ApprovedBy")
                        .WithMany("ApprovedTimeEntries")
                        .HasForeignKey("ApprovedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EIIOS.Models.UserModel", "Employee")
                        .WithMany("TimeEntries")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedBy");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EIIOS.Models.AllergenModel", b =>
                {
                    b.Navigation("ProductAllergens");
                });

            modelBuilder.Entity("EIIOS.Models.CategoryModel", b =>
                {
                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("EIIOS.Models.DailyMenuModel", b =>
                {
                    b.Navigation("DailyMenuItems");
                });

            modelBuilder.Entity("EIIOS.Models.DiscountModel", b =>
                {
                    b.Navigation("DiscountProducts");
                });

            modelBuilder.Entity("EIIOS.Models.InventoryItemModel", b =>
                {
                    b.Navigation("ProductIngredients");

                    b.Navigation("StockEntries");
                });

            modelBuilder.Entity("EIIOS.Models.ProductModel", b =>
                {
                    b.Navigation("DailyMenuItems");

                    b.Navigation("DiscountProducts");

                    b.Navigation("ProductAllergens");

                    b.Navigation("ProductCategories");

                    b.Navigation("ProductIngredients");
                });

            modelBuilder.Entity("EIIOS.Models.UserModel", b =>
                {
                    b.Navigation("ApprovedTimeEntries");

                    b.Navigation("CreatedDailyMenus");

                    b.Navigation("CreatedDiscounts");

                    b.Navigation("CreatedProducts");

                    b.Navigation("CreatedStockEntries");

                    b.Navigation("TimeEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
